name: CI FastAPI
on:
  push:
    paths:
      - "fastapi-app/**"
      - ".github/workflows/ci-fastapi.yml"
  pull_request:
    paths:
      - "fastapi-app/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        working-directory: fastapi-app
        run: pip install -r requirements.txt
      - name: Run tests
        working-directory: fastapi-app
        run: pytest -q --disable-warnings
